### ISSUE TITLE
Some students who have a newer version rake are forced to use bundle exec rake

### ISSUE THREAD

**Issue by hysan** [learn-co-curriculum/mechanics-of-migrations#55]
Some students have a newer version of rake installed (12.x.x) whereas this lab asks for 11.2.2. I updated my rake gem to try and reproduce this, but could not. However, I have seen a student's environment where it was not possible to run any rake commands without using the workaround of `bundle exec rake <command>`.

```
// ♥ rake console
WARN: Unresolved specs during Gem::Specification.reset:
      minitest (~> 5.1)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
rake aborted!
Gem::LoadError: You have already activated rake 12.3.0, but your Gemfile requires rake 11.2.2. Prepending `bundle exec` to your command may solve this.
/Users/thomaslever/.rvm/gems/ruby-2.3.3/gems/bundler-1.16.4/lib/bundler/runtime.rb:313:in `check_for_activated_spec!'
/Users/thomaslever/.rvm/gems/ruby-2.3.3/gems/bundler-1.16.4/lib/bundler/runtime.rb:31:in `block in setup'
/Users/thomaslever/.rvm/gems/ruby-2.3.3/gems/bundler-1.16.4/lib/bundler/runtime.rb:26:in `map'
/Users/thomaslever/.rvm/gems/ruby-2.3.3/gems/bundler-1.16.4/lib/bundler/runtime.rb:26:in `setup'
/Users/thomaslever/.rvm/gems/ruby-2.3.3/gems/bundler-1.16.4/lib/bundler.rb:107:in `setup'
/Users/thomaslever/.rvm/gems/ruby-2.3.3/gems/bundler-1.16.4/lib/bundler/setup.rb:10:in `<top (required)>'
/Users/thomaslever/Development/mechanics-of-migrations-nyc-web-082718/config/environment.rb:8:in `<top (required)>'
/Users/thomaslever/Development/mechanics-of-migrations-nyc-web-082718/Rakefile:1:in `require_relative'
/Users/thomaslever/Development/mechanics-of-migrations-nyc-web-082718/Rakefile:1:in `<top (required)>'
/Users/thomaslever/.rvm/gems/ruby-2.3.3/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
/Users/thomaslever/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:24:in `eval'
/Users/thomaslever/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:24:in `<main>'
```

**Comment by cjbrock** [comment]
Hi @hysan! Using the `bundle exec` command is actually an expected workaround as a developer, and not an issue. 
// Corinna

**Comment by EvansJWang** [comment]
bundle exec WOULD in fact work. However, we are using rvm and we are asking students to lock their ruby versions to 2.3.3 and the labs should seamlessly work with the correct gem versions that are compatible with 2.3.3

**Comment by cjbrock** [comment]
This has been added to Known Issues - it should work, but we'll need some more investigation as to why it doesn't.
